#!/usr/bin/env ruby

require 'bundler/setup'
require 'ib-api'
require 'ib/symbols'
require 'ib/verify'

=begin
Discover properties of Options

IB provides two calculations: :RequestOptionPrice and :RequestImpliedVolatility

ib.send_message :RequestOptionPrice
-----------------------------------
Given a valid option-contract, a fair option-price is calculated using appropiate 
Underlying-price (:under_price) and :volatility-input-values

In addition, the »greeks« and the incorporated dividend are provided by the tws

ib.send_message :RequestImpliedVolatility
-----------------------------------------
Instead of :volatility, the  :option_price is used as input. 

Both requests are answered by a :TickOption-Message and are thus easily displayed by
(in console)
 C.send_message :RequestImpliedVolatility, contract: IB::Symbols::Options.aapl200, under_price: 180, option_price: 11.3 
 => 8673   # returns the ticker_id
C.received[:TickOption].to_human
 => ["<TickOption cust_option_computation for ticker_id: underlying @ 180.0, option @ 11.3, IV 0.16260792724594816%, delta -2.0, gamma -2.0, vega -2.0, theta -2.0, pv_dividend -1.0>"]
...(greeks: -2.0  indicates, that IB has not jet calculated anything, but the IV is there ) 

=end


# First, connect to IB TWS and subscribe for events. 
# The output is produced »on the fly« if the tws-response is detected
# The output is unsorted! 
#
#ib = IB::Connection.new( :client_id => 1102, port: 7496, host: '10.222.148.177'  ) do  | gw | 
	ib = IB::Connection.new( :client_id => 1112   )do | gw | #, :port => 7497 # TWS

		# Subscribe to TWS alerts/errors
		gw.subscribe(:Alert, :ManagedAccounts ) { |msg| puts msg.to_human }

		# the Output
		gw.subscribe( :TickOption ) do |msg| 
			print " %3d %% --->    %6.3f  " % [msg.ticker_id.to_i, msg.option_price]
			puts "   || " + "%7.6f   %6.3f   %6.3f   %6.3f" % [ msg.gamma, msg.delta, msg.theta || -1, msg.vega ]
		end
		# Set log level
		gw.logger.level = Logger::ERROR # DEBUG  -- INFO -- WARN -- ERROR  -- FATAL
	end

	# We use OptionPriceCalculations provided by IB
	# specify the Option
	the_option =  IB::Symbols::Options.aapl.merge( strike: 120 ).verify.first

	# specify the desired Volatility-Range
	vola_range = ( 10 .. 50 ) # in % p.a.

	# Specify the hypothetical price of the underlying

	underlying_price =  100 

	puts "BASE:  #{the_option.to_human}"
	puts "Hypothetical price of the underlying: #{underlying_price}"
	puts
	puts " We simulate the rise of volatility"
	puts '-'*66
	puts  "Vola   --->  Option-Price ||  Gamma     Delta    Theta    Vega "
	puts '-'*66
	# get the prices and store in recieved-array
	vola_range.each do | the_vola |
		req_id = ib.send_message :RequestOptionPrice, 
		id:  the_vola,
		contract: the_option,
		volatility: the_vola.to_f/100,
		under_price: underlying_price
	ib.wait_for :TickOption, 1

	ib.send_message :CancelOptionPrice, id: req_id
	end
	sleep 2
	puts "Thats it, folks"


=begin 
Expected Output

BASE:  <Option: AAPL 20201218 call 120.0 SMART USD>
Hypothetical price of the underlying: 100
(the date: Oct. 26th)
 We simulate the rise of volatility
------------------------------------------------------------------
Vola   --->  Option-Price ||  Gamma     Delta    Theta    Vega 
------------------------------------------------------------------
  10 % --->     0.000     || 0.000001    0.000   -1.000    0.000
  16 % --->     0.002     || 0.000664    0.001   -1.000    0.002
  17 % --->     0.004     || 0.001086    0.002   -1.000    0.004
  18 % --->     0.008     || 0.001625    0.004   -1.000    0.005
  19 % --->     0.013     || 0.002237    0.006   -1.000    0.007
  20 % --->     0.020     || 0.002921    0.008   -1.000    0.011
  21 % --->     0.031     || 0.003728    0.011   -1.000    0.012
  22 % --->     0.042     || 0.004450    0.015   -1.000    0.018
  23 % --->     0.060     || 0.005344    0.019   -1.000    0.018
  24 % --->     0.078     || 0.006098    0.023   -1.000    0.025
  25 % --->     0.102     || 0.006935    0.029   -1.000    0.027
  26 % --->     0.129     || 0.007706    0.034   -1.000    0.027
  27 % --->     0.157     || 0.008352    0.039   -1.000    0.039
  28 % --->     0.196     || 0.009119    0.046   -1.000    0.039
  29 % --->     0.235     || 0.009763    0.053   -1.000    0.039
  30 % --->     0.274     || 0.010301    0.058   -1.000    0.049
  31 % --->     0.322     || 0.010860    0.065   -1.000    0.054
  32 % --->     0.376     || 0.011385    0.073   -1.000    0.054
  33 % --->     0.430     || 0.011827    0.079   -1.000    0.054
  34 % --->     0.483     || 0.012198    0.086   -1.000    0.059
  35 % --->     0.543     || 0.012538    0.092   -1.000    0.071
  36 % --->     0.614     || 0.012883    0.100   -1.000    0.071
  37 % --->     0.685     || 0.013173    0.107   -1.000    0.071
  38 % --->     0.756     || 0.013415    0.114   -1.000    0.071
  39 % --->     0.827     || 0.013614    0.121   -1.000    0.071
  40 % --->     0.898     || 0.013777    0.127   -1.000    0.082
  41 % --->     0.980     || 0.013927    0.133   -1.000    0.090
  42 % --->     1.070     || 0.014062    0.141   -1.000    0.090
  43 % --->     1.161     || 0.014169    0.148   -1.000    0.090
  44 % --->     1.251     || 0.014252    0.154   -1.000    0.090
  45 % --->     1.342     || 0.014314    0.160   -1.000    0.090
  46 % --->     1.432     || 0.014356    0.166   -1.000    0.090
  47 % --->     1.522     || 0.014382    0.172   -1.000    0.090
  48 % --->     1.613     || 0.014393    0.178   -1.000    0.099
  49 % --->     1.712     || 0.014390    0.184   -1.000    0.110
  50 % --->     1.822     || 0.014376    0.190   -1.000    0.110
  11 % --->     0.000     || 0.000004    0.000   -1.000    0.000
  12 % --->     0.000     || 0.000021    0.000   -1.000    0.000
  13 % --->     0.000     || 0.000071    0.000   -1.000    0.000
  14 % --->     0.000     || 0.000178    0.000   -1.000    0.001
  15 % --->     0.001     || 0.000367    0.001   -1.000    0.001
Thats it, folks
=end
