#!/usr/bin/env ruby
#
## This script places WFC buy  what-if order for 100 lots 
## and estimates commision, margin requirements and verifies that its executable.
## It does not place the order for execution.
#
require 'bundler/setup'
require 'ib-api'
require 'ib/order-prototypes'

# you need to provide account_code such as U666777
account_code = ARGV[0] || ''
#
# First, connect to IB TWS. Arbitrary :client_id is used to identify your script
ib = IB::Connection.new client_id: 1112  do | gw | #, :port => 7496 # TWS

# Subscribe to TWS alerts/errors and order-related messages prior to the connection of the client
  gw.subscribe(:Alert, :OpenOrder, :OrderStatus,  :ManagedAccounts, :OpenOrderEnd ) { |msg| puts "recieved: #{msg.to_human }" }

end
wfc = IB::Stock.new symbol: 'WFC'

puts "-" * 80
puts IB::Limit.summary
puts "Supported Parameter"
puts "-" * 80
puts IB::Limit.parameters
buy_order = IB::Limit.order size: 100,
                          price: 1 + rand().round(2),
                          action:  :buy,
													what_if: true,
													account: account_code
puts "placing #{buy_order.to_human}"
ib.wait_for :NextValidId
ib.place_order buy_order,  wfc
ib.wait_for :OpenOrder, 5 #sec

puts "Got OpenOrder message"
#ib.send_message :RequestAllOpenOrders


#puts ib.received[:OpenOrder].last.order.inspect

recieved_order = ib.received[:OpenOrder].last.order
recieved_status =  recieved_order.order_states.last
#puts recieved_status.to_human
puts ""
puts  '*' * 80
puts  "Summary for a placement of #{buy_order.total_quantity} shares of #{wfc.to_human} on #{account_code}"
puts  '_' * 80
puts  ""
puts  "Available Cash (equity with loan) \t #{recieved_status[:equity_with_loan].to_f}"
puts  "Margin usage after placement \t (init) #{recieved_status[:init_margin].to_f} \t (maint.) #{recieved_status[:maint_margin].to_f} "
puts  "Commissions \t \t \t (min) #{recieved_status[:min_commission].to_f}  \t\t (max) #{recieved_status[:max_commission].to_f} "

puts ""
puts  '*' * 80
#### Expected Output
#
#Connected to server, version: 137,
# connection time: 2020-10-16 05:07:08 +0000 local, 2020-10-16T05:07:07+00:00 remote.
#recieved: < ManagedAccounts: DF167347 - DU167348 - DU167349>
#Got next valid order id: 104.
#--------------------------------------------------------------------------------
#	A Limit order is an order to buy or sell at a specified price or better. 
#	The Limit order ensures that if the order fills, it will not fill at a price less favorable than 
#	your limit price, but it does not guarantee a fill. 
#	It appears in the orderbook.
#Supported Parameter
#--------------------------------------------------------------------------------
#Required : action --> {"B"=>:buy, "S"=>:sell, "T"=>:short, "X"=>:short_exempt}
#	: total_quantity --> also aliased as :size
#	: limit_price --> also aliased as :price
# --------------- 
#Optional : account --> Account(number) to trade on
# --------------- 
#placing <Order: LMT GTC buy 100  @ 1.0 New #/ from /DU167349>
#recieved: <OpenOrder: <Stock: WFC USD> <Order: LMT GTC buy 100.0  @ 1.0 PreSubmitted #104/988357646 from 0/DU167349>>
#Got OpenOrderEnd message
#
#********************************************************************************
#Summary for a placement of 100 shares of <Stock: WFC USD> on DU167349
#________________________________________________________________________________
#
#Available Cash (equity with loan) 	 891888.27
#Margin requirements 	 	 (init) 53170.9 	 (maint.) 50222.84 
#Commissions 	 	 	 (min) 0.9  		 (max) 1.0 
#
#********************************************************************************
#
